[package]
name = "shadow_company_tools_derive"
version = "0.0.1"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = "2.0"
quote = "1.0"
shadow_company_tools = { path = "../" }
proc-macro2 = "1.0"
