[package]
name = "raw2png"
version = "0.1.0"
edition = "2021"

[dependencies]
shadow_company_tools = { path = "../../" }
clap = { version = "4.5", features = ["derive"] }
image = "*"
thiserror = "2.0.3"
