[package]
name = "smf"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.1", features = ["derive"] }
shadow_company_tools = { path = "../.." }
walkdir = { version = "2.5.0", default-features = false }
