[package]
name = "smf"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
ptree = { version = "0.5", default-features = false }
shadow_company_tools = { path = "../.." }
walkdir = { version = "2.5", default-features = false }
