[package]
name = "campaigns"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.1", features = ["derive"] }
prettytable-rs = { version = "0.10.0", default-features = false }
shadow_company_tools = { path = "../.." }
shadow_company_tools_configs = { path = "../../configs" }
